module.exports = async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { imageBase64, mimeType } = req.body;

    if (!imageBase64) {
      return res.status(400).json({ error: 'No image provided' });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error('CRITICAL: Missing GEMINI_API_KEY environment variable');
      return res.status(500).json({ error: 'Server configuration error: Missing API Key' });
    }

    // Strip the "data:image/jpeg;base64," prefix if it was passed from the frontend
    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, '');

    const prompt = `You are an elite automotive safety inspector and headlight restoration specialist operating on Vancouver Island, BC.
Conduct a highly granular, professional diagnostic analysis of the provided vehicle headlight image.

Respond ONLY with a valid JSON object in exactly this format, with no extra text:

{
  "overall_health_score": <number 1.0 to 10.0, with 1 decimal place. 10 is factory new>,
  "condition_category": "<Critical | Poor | Fair | Good | Excellent>",
  "safety_impact": {
    "is_hazardous": <true or false - true if condition severely impacts night driving>,
    "visibility_reduction_percent": <number 0-100 - how much light is blocked>,
    "lost_reaction_time_seconds": <number 0.0 to 3.5 - estimated seconds of delayed reaction at 80km/h due to dim light throw>,
    "collision_risk_increase_percent": <number 0 to 400 - estimated percentage increase in night-time accident risk>,
    "driver_warning": "<A stark, honest 1-sentence warning about driving with these specific headlights at night or in rain.>"
  },
  "damage_metrics": {
    "oxidation_yellowing_percent": <number 0-100>,
    "clearcoat_failure_percent": <number 0-100>,
    "surface_pitting_percent": <number 0-100>
  },
  "clinical_findings": [
    "<Specific, technical observation 1>",
    "<Specific, technical observation 2>"
  ],
  "restoration_protocol": {
    "recommended_treatment": "<Specific detailing steps>",
    "expected_clarity_recovery_percent": <number 0-100>
  },
  "is_restorable": <true or false>
}

Diagnostic Guidelines:
- Be highly analytical. A 10/10 means showroom floor.
- For scores under 6.0, heavily emphasize the 'safety_impact' metrics. 
- Calibrate 'lost_reaction_time_seconds' accurately: severely cloudy lenses can reduce beam distance enough to lose 1-2 full seconds of highway reaction time.
- If the image is NOT a headlight, set "is_restorable" to false and state it in the findings.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [{
            parts: [
              { text: prompt },
              {
                inline_data: {
                  mime_type: mimeType || 'image/jpeg',
                  data: cleanBase64
                }
              }
            ]
          }],
          generationConfig: {
            temperature: 0.2,
            maxOutputTokens: 1024,
            responseMimeType: "application/json"
          }
        })
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API returned an error:', errorText);
      return res.status(500).json({ error: 'Gemini API rejected the request', details: errorText });
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
      console.error('Gemini API returned an empty response:', JSON.stringify(data));
      return res.status(500).json({ error: 'No text generated by Gemini' });
    }

    // Because of responseMimeType: "application/json", the text is guaranteed to be pure JSON.
    // No more manual string slicing needed!
    const parsed = JSON.parse(text);

    return res.status(200).json(parsed);

  } catch (error) {
    console.error('Server function crashed:', error);
    return res.status(500).json({ error: 'Internal Server Error', details: error.message });
  }
};