module.exports = async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { imageBase64, mimeType } = req.body;

    if (!imageBase64) {
      return res.status(400).json({ error: 'No image provided' });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error('CRITICAL: Missing GEMINI_API_KEY environment variable');
      return res.status(500).json({ error: 'Server configuration error: Missing API Key' });
    }

    // Strip the "data:image/jpeg;base64," prefix if it was passed from the frontend
    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, '');

    const prompt = `You are an elite automotive safety inspector and headlight restoration specialist operating on Vancouver Island, BC.

STEP 1 — IS THIS A HEADLIGHT?
Before doing anything else, look at the image and determine: is this a vehicle headlight or headlamp lens?

If it is NOT a headlight (e.g. car door, bumper, mirror, tire, interior, person, animal, food, anything else), you MUST respond with ONLY this exact JSON and nothing else:
{"is_headlight": false}

Do NOT provide scores, findings, metrics, or recommendations for non-headlight images. Just return that single object and stop.

STEP 2 — HEADLIGHT ANALYSIS (only if it IS a headlight)
If the image is a vehicle headlight, conduct a professional diagnostic analysis. Be consistent and objective — base all scores strictly on the visual evidence in the image. The same image should always produce the same scores.

Respond ONLY with a valid JSON object using this exact structure:

{
  "is_headlight": true,
  "overall_health_score": 0.0,
  "condition_category": "",
  "safety_impact": {
    "is_hazardous": false,
    "visibility_reduction_percent": 0,
    "lost_reaction_time_seconds": 0.0,
    "collision_risk_increase_percent": 0,
    "driver_warning": ""
  },
  "damage_metrics": {
    "oxidation_yellowing_percent": 0,
    "clearcoat_failure_percent": 0,
    "surface_pitting_percent": 0
  },
  "clinical_findings": [
    ""
  ],
  "restoration_protocol": {
    "recommended_treatment": "5-Stage Professional Restoration — Book as soon as possible",
    "expected_clarity_recovery_percent": 97
  },
  "is_restorable": true
}

Diagnostic Guidelines:
- "overall_health_score": Number from 1.0 to 10.0 (10 is factory new). Base this on what you actually see — do not randomize.
- "condition_category": Must be one of: Critical, Poor, Fair, Good, Excellent.
- "driver_warning": A stark, honest 1-sentence warning and nudge to get them restored soon, without any line breaks. Only include if the lens genuinely needs attention (score below 8).
- Calibrate "lost_reaction_time_seconds" accurately: severely cloudy lenses can reduce beam distance enough to lose 1-5 full seconds of highway reaction time.
- "restoration_protocol": Always set recommended_treatment to "5-Stage Professional Restoration — Book as soon as possible" and expected_clarity_recovery_percent to 97. Do not invent alternatives.
- IMPORTANT: Ensure all strings in the JSON are properly escaped and do not contain actual line breaks.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [{
            parts: [
              { text: prompt },
              {
                inline_data: {
                  mime_type: mimeType || 'image/jpeg',
                  data: cleanBase64
                }
              }
            ]
          }],
          generationConfig: {
            temperature: 0.1,
            maxOutputTokens: 2048,
            responseMimeType: "application/json"
          }
        })
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API returned an error:', errorText);
      return res.status(500).json({ error: 'Gemini API rejected the request', details: errorText });
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
      console.error('Gemini API returned an empty response:', JSON.stringify(data));
      return res.status(500).json({ error: 'No text generated by Gemini' });
    }

    let parsed;
    try {
      parsed = JSON.parse(text);
    } catch (parseError) {
      console.error('Failed to parse JSON. Raw text from Gemini:', text);
      return res.status(500).json({ error: 'Invalid JSON format from AI', raw: text });
    }

    return res.status(200).json(parsed);

  } catch (error) {
    console.error('Server function crashed:', error);
    return res.status(500).json({ error: 'Internal Server Error', details: error.message });
  }
};
